#!/usr/bin/env python3
"""
Pull Request management script for GitHub Actions workflows.

Handles PR creation with proper Trace_ID and Issue linking.
"""

import os
import sys
import argparse
import re
from pathlib import Path
from typing import Optional

# Add the app directory to the Python path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "app"))

from github_client import GitHubClient, GitHubClientError


def extract_trace_id_from_issue(github_client: GitHubClient, issue_number: int) -> Optional[str]:
    """
    Extract Trace_ID from issue body.
    
    Args:
        github_client: GitHub client instance
        issue_number: Issue number
        
    Returns:
        Trace_ID if found, None otherwise
    """
    try:
        issue = github_client.get_issue(issue_number)
        issue_body = issue.body or ""
        
        # Look for Trace_ID pattern: **Trace_ID**: `trace-...`
        trace_pattern = r'\*\*Trace_ID\*\*:\s*`([^`]+)`'
        match = re.search(trace_pattern, issue_body)
        
        if match:
            return match.group(1)
        
        # Fallback: look for any trace- pattern
        fallback_pattern = r'trace-[a-zA-Z0-9\-_]+'
        match = re.search(fallback_pattern, issue_body)
        
        if match:
            return match.group(0)
        
        return None
    except Exception as e:
        print(f"⚠️ Warning: Could not extract Trace_ID from issue #{issue_number}: {e}")
        return None


def create_implementation_pr(
    issue_number: int,
    branch_name: str,
    base_branch: str = "main"
) -> int:
    """
    Create a Pull Request for implementation.
    
    Args:
        issue_number: GitHub Issue number
        branch_name: Branch name containing implementation
        base_branch: Base branch to merge into (default: "main")
        
    Returns:
        Pull Request number
        
    Raises:
        GitHubClientError: If PR creation fails
    """
    try:
        github_client = GitHubClient()
        
        # Get issue details
        issue = github_client.get_issue(issue_number)
        issue_title = issue.title
        
        # Extract Trace_ID
        trace_id = extract_trace_id_from_issue(github_client, issue_number)
        if not trace_id:
            trace_id = f"impl-{issue_number}-{os.getenv('GITHUB_RUN_ID', 'unknown')}"
            print(f"⚠️ No Trace_ID found, generated: {trace_id}")
        
        # Create PR title
        pr_title = f"Implementation: {issue_title}"
        
        # Create PR body with Trace_ID and Issue reference
        pr_body = f"""## Implementation for Issue #{issue_number}

Fixes #{issue_number}

**Trace_ID**: `{trace_id}`

### Implementation Summary

This PR implements the solution based on the approved implementation plan.

### Changes Made

- Code changes generated with repository context awareness
- Unit tests included for all new/modified code
- All tests passing

### Testing

- ✅ Unit tests added and passing
- ✅ Integration tests verified
- ✅ Code follows existing patterns and conventions

---

*This implementation was generated by the automated workflow system with Claude CLI for enhanced repository awareness.*
"""
        
        # Create the pull request
        pr = github_client.create_pull_request(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=base_branch,
            labels=["agent:claude"]
        )
        
        print(f"✅ Created Pull Request #{pr.number}")
        print(f"📋 Title: {pr_title}")
        print(f"🔗 URL: {pr.html_url}")
        print(f"🏷️ Trace_ID: {trace_id}")
        
        return pr.number
        
    except GitHubClientError as e:
        print(f"❌ Failed to create Pull Request: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Unexpected error creating Pull Request: {e}")
        sys.exit(1)


def main():
    """Main entry point for PR manager."""
    parser = argparse.ArgumentParser(description="Pull Request Manager")
    parser.add_argument("action", choices=["create"],
                       help="Action to perform")
    parser.add_argument("--issue-id", type=int, required=True,
                       help="GitHub Issue ID")
    parser.add_argument("--branch", type=str, required=True,
                       help="Branch name containing implementation")
    parser.add_argument("--base", type=str, default="main",
                       help="Base branch to merge into (default: main)")
    
    args = parser.parse_args()
    
    if args.action == "create":
        pr_number = create_implementation_pr(
            issue_number=args.issue_id,
            branch_name=args.branch,
            base_branch=args.base
        )
        
        # Output for GitHub Actions
        if "GITHUB_OUTPUT" in os.environ:
            with open(os.environ["GITHUB_OUTPUT"], "a") as f:
                f.write(f"pr_number={pr_number}\n")
        
        sys.exit(0)
    else:
        print(f"Unknown action: {args.action}")
        sys.exit(1)


if __name__ == "__main__":
    main()
